mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=test
    - MYSQL_PASSWORD=testing
    - MYSQL_DATABASE=community
    - MYSQL_ROOT_PASSWORD=root
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"